In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [ ]:
df = pd.read_csv('/content/parkinsons.csv');

In [ ]:
df.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

PREPROCESSING

In [ ]:
df.shape

(195, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [ ]:
df.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Length: 195, dtype: bool

In [ ]:
df.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,154.228641,197.104918,116.324631,0.006220,0.000044,0.003306,0.003446,0.009920,0.029709,0.282251,...,0.046993,0.024847,21.885974,0.753846,0.498536,0.718099,-5.684397,0.226510,2.381826,0.206552
std,41.390065,91.491548,43.521413,0.004848,0.000035,0.002968,0.002759,0.008903,0.018857,0.194877,...,0.030459,0.040418,4.425764,0.431878,0.103942,0.055336,1.090208,0.083406,0.382799,0.090119
min,88.333000,102.145000,65.476000,0.001680,0.000007,0.000680,0.000920,0.002040,0.009540,0.085000,...,0.013640,0.000650,8.441000,0.000000,0.256570,0.574282,-7.964984,0.006274,1.423287,0.044539
25%,117.572000,134.862500,84.291000,0.003460,0.000020,0.001660,0.001860,0.004985,0.016505,0.148500,...,0.024735,0.005925,19.198000,1.000000,0.421306,0.674758,-6.450096,0.174351,2.099125,0.137451
50%,148.790000,175.829000,104.315000,0.004940,0.000030,0.002500,0.002690,0.007490,0.022970,0.221000,...,0.038360,0.011660,22.085000,1.000000,0.495954,0.722254,-5.720868,0.218885,2.361532,0.194052
75%,182.769000,224.205500,140.018500,0.007365,0.000060,0.003835,0.003955,0.011505,0.037885,0.350000,...,0.060795,0.025640,25.075500,1.000000,0.587562,0.761881,-5.046192,0.279234,2.636456,0.252980
max,260.105000,592.030000,239.170000,0.033160,0.000260,0.021440,0.019580,0.064330,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.685151,0.825288,-2.434031,0.450493,3.671155,0.527367

In [ ]:
df['status'].value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [ ]:
# 1-> parkinson +ve
# 0-> parkinson -ve

In [ ]:
df.groupby('status').mean(numeric_only=True)

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
status,,,,,,,,,,,,,,,,,,,,,
0,181.937771,223.636750,145.207292,0.003866,0.000023,0.001925,0.002056,0.005776,0.017615,0.162958,...,0.013305,0.028511,0.011483,24.678750,0.442552,0.695716,-6.759264,0.160292,2.154491,0.123017
1,145.180762,188.441463,106.893558,0.006989,0.000051,0.003757,0.003900,0.011273,0.033658,0.321204,...,0.027600,0.053027,0.029211,20.974048,0.516816,0.725408,-5.333420,0.248133,2.456058,0.233828

In [ ]:
X = df.drop(columns=['name','status'],axis =1)
y = df['status']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
scalar = StandardScaler()

In [ ]:
scalar.fit(X_train)
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)

In [ ]:
X_train[:5]

array([[ 0.63239631, -0.02731081, -0.87985049,  0.36806203,  0.14406765,
         0.49280653,  0.30476869,  0.49170115, -0.3137565 , -0.32592164,
        -0.25848708, -0.23791175, -0.33873289, -0.25879402, -0.2113724 ,
        -0.61257363,  0.87112118,  0.24786644,  0.19888239, -0.97586547,
        -0.55160318,  0.07769494],
       [-1.05512719, -0.83337041, -0.9284778 , -0.12997764,  0.14406765,
        -0.15236125, -0.14436412, -0.15344933,  0.44321834,  0.51889992,
        -0.06490951,  0.09074355,  0.86575291, -0.06521554, -0.15277503,
        -0.2558165 ,  1.46329474, -0.46857462,  0.42875723,  0.3981808 ,
        -0.61014073,  0.39291782],
       [ 0.02996187, -0.29531068, -1.12211107, -0.55550578, -0.67219944,
        -0.47338676, -0.54959672, -0.47446624,  0.29594502,  0.0409723 ,
         0.38677148,  0.3503336 ,  0.12088079,  0.38646758, -0.42840806,
         0.12878192,  0.05032775, -0.13964197, -0.51631148, -0.43937044,
        -0.62849605, -0.50948408],
       [-0.97953968, -0.77220159, -0.17874128,  0.19632421,  0.41615668,
        -0.15236125,  0.37230746, -0.15137155, -0.41931076, -0.37419715,
        -0.42962087, -0.33396801, -0.32935302, -0.42930518, -0.46649635,
         0.2578447 ,  0.31415019,  1.83380438,  0.94121474,  0.76057089,
        -0.93717842,  1.13851269],
       [ 0.68311164, -0.0343547 ,  1.09197003, -0.74632558, -0.94428847,
        -0.66662542, -0.7150667 , -0.66562193, -0.8365014 , -0.80384926,
        -0.84763619, -0.77693819, -0.72330761, -0.84763419, -0.56205515,
         1.04258088, -1.78606353,  0.7394244 , -1.21943739, -1.90615891,
        -0.07889448, -0.99301174]])

MODEL TRAINING

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(X_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred = model.predict(X_test)
accuracy_score(y_test,y_pred)

0.8717948717948718

In [ ]:
precision_score(y_test,y_pred)

0.90625

In [ ]:
recall_score(y_test,y_pred)

0.9354838709677419

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 5,  3],
       [ 2, 29]])

Getting best parameter using optuna

In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-5.0.0-py3-none-any.whl.metadata (14 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.5)
Downloading optuna-5.0.0-py3-none-any.whl (442 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 4.7 MB/s eta 0:00:00
Downloading alembic-1.19.2-py3-none-any.whl (267 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.4/267.4 kB 20.1 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.19.2 colorlog-6.12.0 optuna-5.0.0

In [ ]:
import optuna


def objective(trial):

    # Hyperparameters to tune
    C = trial.suggest_float("C", 0.01, 100, log=True)

    kernel = trial.suggest_categorical(
        "kernel", ["linear", "rbf", "poly"]
    )

    gamma = trial.suggest_categorical(
        "gamma", ["scale", "auto"]
    )

    # Create model
    model = svm.SVC(
        C=C,
        kernel=kernel,
        gamma=gamma
    )

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Evaluate
    accuracy = accuracy_score(y_test, y_pred)

    return accuracy


# Create and run study
study = optuna.create_study(direction="maximize")

study.optimize(objective, n_trials=50)


# Best parameters
print("Best Parameters:")
print(study.best_params)

print("\nBest Accuracy:")
print(study.best_value)

[I 2026-09-10 18:22:50,663] A new study created in memory with name: no-name-b299afea-262c-4108-9d15-285bfb97324e
[I 2026-09-10 18:22:50,676] Trial 0 finished with value: 0.8717948717948718 and parameters: {'C': 0.7664625250776486, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:50,685] Trial 1 finished with value: 0.8205128205128205 and parameters: {'C': 0.1224019938773618, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:50,953] Trial 2 finished with value: 0.7948717948717948 and parameters: {'C': 82.28602392588249, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:50,963] Trial 3 finished with value: 0.7948717948717948 and parameters: {'C': 2.960542479758451, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:50,972] Trial 4 finished with value: 0.8461538461538461 and parameters: {'C': 0.41162669553322845, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:50,985] Trial 5 finished with value: 0.8717948717948718 and parameters: {'C': 0.8220430115521655, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,004] Trial 6 finished with value: 0.8461538461538461 and parameters: {'C': 3.3458488146011645, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,012] Trial 7 finished with value: 0.8461538461538461 and parameters: {'C': 24.90189685627562, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,021] Trial 8 finished with value: 0.8717948717948718 and parameters: {'C': 0.038842703381710864, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,030] Trial 9 finished with value: 0.7948717948717948 and parameters: {'C': 2.0236077428791988, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,047] Trial 10 finished with value: 0.7948717948717948 and parameters: {'C': 0.012083098115673662, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,061] Trial 11 finished with value: 0.8717948717948718 and parameters: {'C': 0.856157747976124, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,090] Trial 12 finished with value: 0.8717948717948718 and parameters: {'C': 9.02761922100773, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,107] Trial 13 finished with value: 0.8461538461538461 and parameters: {'C': 0.2040000661162107, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,123] Trial 14 finished with value: 0.8461538461538461 and parameters: {'C': 0.13617351172278122, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,135] Trial 15 finished with value: 0.7948717948717948 and parameters: {'C': 0.015852180632668963, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 0 with value: 0.8717948717948718.
[I 2026-09-10 18:22:51,146] Trial 16 finished with value: 0.8974358974358975 and parameters: {'C': 1.163000867137722, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,168] Trial 17 finished with value: 0.8974358974358975 and parameters: {'C': 0.8991224949553773, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,200] Trial 18 finished with value: 0.8974358974358975 and parameters: {'C': 0.8241181881800288, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,220] Trial 19 finished with value: 0.8717948717948718 and parameters: {'C': 10.151667723324119, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,242] Trial 20 finished with value: 0.8717948717948718 and parameters: {'C': 0.2540550737757848, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,254] Trial 21 finished with value: 0.8974358974358975 and parameters: {'C': 1.3278558735117252, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,264] Trial 22 finished with value: 0.8461538461538461 and parameters: {'C': 0.6078584866749378, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,278] Trial 23 finished with value: 0.7948717948717948 and parameters: {'C': 5.822491544518894, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,293] Trial 24 finished with value: 0.8974358974358975 and parameters: {'C': 0.6080197982091294, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,303] Trial 25 finished with value: 0.8717948717948718 and parameters: {'C': 3.544858453511243, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,313] Trial 26 finished with value: 0.8717948717948718 and parameters: {'C': 0.11694705371685778, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,323] Trial 27 finished with value: 0.8205128205128205 and parameters: {'C': 0.08524198610498304, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,335] Trial 28 finished with value: 0.8974358974358975 and parameters: {'C': 46.80334905377405, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,352] Trial 29 finished with value: 0.8205128205128205 and parameters: {'C': 13.20411820087546, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,363] Trial 30 finished with value: 0.8205128205128205 and parameters: {'C': 22.428355213857877, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,390] Trial 31 finished with value: 0.8974358974358975 and parameters: {'C': 1.2605790288206316, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,414] Trial 32 finished with value: 0.8974358974358975 and parameters: {'C': 1.4768408300545555, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,430] Trial 33 finished with value: 0.8717948717948718 and parameters: {'C': 0.30214961262183476, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,441] Trial 34 finished with value: 0.8974358974358975 and parameters: {'C': 0.9437120263870844, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,457] Trial 35 finished with value: 0.8974358974358975 and parameters: {'C': 2.749887812656142, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,471] Trial 36 finished with value: 0.8974358974358975 and parameters: {'C': 2.4708502972451396, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,484] Trial 37 finished with value: 0.8717948717948718 and parameters: {'C': 0.4258433800065825, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,496] Trial 38 finished with value: 0.7948717948717948 and parameters: {'C': 0.03933476180392633, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,509] Trial 39 finished with value: 0.8717948717948718 and parameters: {'C': 0.5708150269174245, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,529] Trial 40 finished with value: 0.7948717948717948 and parameters: {'C': 0.02679777246394168, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,542] Trial 41 finished with value: 0.8974358974358975 and parameters: {'C': 0.9400809450896597, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,553] Trial 42 finished with value: 0.8205128205128205 and parameters: {'C': 5.495018299247395, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,569] Trial 43 finished with value: 0.8974358974358975 and parameters: {'C': 0.6234774586288659, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,584] Trial 44 finished with value: 0.8205128205128205 and parameters: {'C': 1.4643943366768046, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,598] Trial 45 finished with value: 0.8205128205128205 and parameters: {'C': 5.471498094052316, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,607] Trial 46 finished with value: 0.8974358974358975 and parameters: {'C': 1.8954297400482898, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,637] Trial 47 finished with value: 0.8205128205128205 and parameters: {'C': 38.609907692584706, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,653] Trial 48 finished with value: 0.8461538461538461 and parameters: {'C': 1.048247948778231, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.8974358974358975.
[I 2026-09-10 18:22:51,664] Trial 49 finished with value: 0.8717948717948718 and parameters: {'C': 97.46934050711631, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.8974358974358975.

Best Parameters:
{'C': 1.163000867137722, 'kernel': 'poly', 'gamma': 'auto'}

Best Accuracy:
0.8974358974358975

In [ ]:
model = svm.SVC(**study.best_params)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test,y_pred)

0.8974358974358975

In [ ]:
precision_score(y_test,y_pred)

0.8857142857142857

In [ ]:
recall_score(y_test,y_pred)

1.0

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 4,  4],
       [ 0, 31]])

SVM = FINAL MODEL

In [ ]:
final_model = model